apiVersion: v1
kind: ServiceAccount
metadata:
  name: public-user
  namespace: registration
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: public-user
rules:
- apiGroups: ["apps.edgenet.io"]
  resources: ["authorityrequests", "userregistrationrequests", "logins"]
  verbs: ["create"]
- apiGroups: ["apps.edgenet.io"]
  resources: ["emailverifications"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["apps.edgenet.io"]
  resources: ["authorities"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: public-user
roleRef:
  kind: ClusterRole
  name: public-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: public-user
  namespace: registration
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: public-user
  namespace: authority-edgenet
rules:
- apiGroups: ["apps.edgenet.io"]
  resources: ["nodecontributions"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: public-user
  namespace: authority-edgenet
roleRef:
  kind: Role
  name: public-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: public-user
  namespace: registration
