language: go

go:
  - 1.14
  - tip

env:
  - GO111MODULE=on

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    env:
    - BUILD_MODE=e2e
  - os: linux
    env:
    - BUILD_MODE=test

notifications:
  email: false

#before_install:
#  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

script:
  - $GOPATH/bin/goveralls -service=travis-pro
  - make sync
  - make all
  - make test
  - make build
  - make run
  - make clean
  #- make lint test

before_script:
  - git lfs pull
  - go get github.com/mattn/goveralls
