apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RoleLimitation
metadata:
  name: slice
spec:
  match:
    namespaceSelector:
      matchExpressions:
      - key: owner
        operator: In
        values: ["slice"]
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role"]
  parameters:
    rules:
      - resource: selectivedeployments
        verbs: ["*"]
      - resource: configmaps
        verbs: ["*"]
      - resource: endpoints
        verbs: ["*"]
      - resource: persistentvolumeclaims
        verbs: ["*"]
      - resource: pods
        verbs: ["*"]
      - resource: pods/exec
        verbs: ["*"]
      - resource: pods/log
        verbs: ["*"]
      - resource: replicationcontrollers
        verbs: ["*"]
      - resource: services
        verbs: ["*"]
      - resource: secrets
        verbs: ["*"]
      - resource: daemonsets
        verbs: ["*"]
      - resource: deployments
        verbs: ["*"]
      - resource: replicasets
        verbs: ["*"]
      - resource: statefulsets
        verbs: ["*"]
      - resource: horizontalpodautoscalers
        verbs: ["*"]
      - resource: cronjobs
        verbs: ["*"]
      - resource: jobs
        verbs: ["*"]
      - resource: ingresses
        verbs: ["*"]
      - resource: networkpolicies
        verbs: ["*"]
      - resource: replicationcontrollers
        verbs: ["*"]
      - resource: events
        verbs: ["get", "list", "watch"]
      - resource: controllerrevisions
        verbs: ["get", "list", "watch"]
      - resource: roles
        verbs: ["*"]
      - resource: rolebindings
        verbs: ["*"]
