/*
Copyright 2020 Sorbonne Université

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package nodecontribution

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"reflect"
	"syscall"
	"time"

	corev1alpha "github.com/EdgeNet-project/edgenet/pkg/apis/core/v1alpha"
	"github.com/EdgeNet-project/edgenet/pkg/generated/clientset/versioned"
	coreinformerv1alpha "github.com/EdgeNet-project/edgenet/pkg/generated/informers/externalversions/core/v1alpha"
	"github.com/EdgeNet-project/edgenet/pkg/node"

	log "github.com/sirupsen/logrus"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/cache"
	"k8s.io/client-go/util/workqueue"
)

// The main structure of controller
type controller struct {
	logger       *log.Entry
	queue        workqueue.RateLimitingInterface
	informer     cache.SharedIndexInformer
	nodeInformer cache.SharedIndexInformer
	handler      HandlerInterface
}

// The main structure of informerevent
type informerevent struct {
	key      string
	function string
}

// Constant variables for events
const inqueue = "In Queue"
const inprogress = "In Progress"
const failure = "Failure"
const incomplete = "Halting"
const success = "Successful"
const create = "create"
const update = "update"
const delete = "delete"
const trueStr = "True"
const falseStr = "False"
const unknownStr = "Unknown"

// Dictionary of status messages
var statusDict = map[string]string{
	"successful":              "Node is up and running",
	"failure":                 "Node is unready",
	"in-progress":             "Node setup in progress",
	"invalid-host":            "Error: Host field must be an IP Address",
	"ssh-failure":             "Error: SSH handshake failed",
	"join-failure":            "Error: Node cannot join the cluster",
	"configuration-failure":   "Error: Scheduling configuration failed",
	"owner-reference-failure": "Error: Setting owner reference failed",
	"reboot-failure":          "Error: Node cannot get rebooted",
	"timeout":                 "Error: Node contribution failed due to timeout",
}

// Start function is entry point of the controller
func Start(kubernetes kubernetes.Interface, edgenet versioned.Interface) {
	var err error
	clientset := kubernetes
	edgenetClientset := edgenet

	NCHandler := &Handler{}
	// Create the nodecontribution informer which was generated by the code generator to list and watch nodecontribution resources
	informer := coreinformerv1alpha.NewNodeContributionInformer(
		edgenetClientset,
		0,
		cache.Indexers{},
	)
	// Create a work queue which contains a key of the resource to be handled by the handler
	queue := workqueue.NewRateLimitingQueue(workqueue.DefaultControllerRateLimiter())
	var event informerevent
	// Event handlers deal with events of resources. Here, there are three types of events as Add, Update, and Delete
	informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
			if queue.Len() == 0 {
				// Put the resource object into a key
				event.key, err = cache.MetaNamespaceKeyFunc(obj)
				event.function = create
				log.Infof("Add nodecontribution: %s", event.key)
				if err == nil {
					// Add the key to the queue
					queue.Add(event)
				}
			} else {
				ncCopy := obj.(*corev1alpha.NodeContribution).DeepCopy()
				ncCopy.Status.State = inqueue
				edgenetClientset.CoreV1alpha().NodeContributions().UpdateStatus(context.TODO(), ncCopy, metav1.UpdateOptions{})
			}
		},
		UpdateFunc: func(oldObj, newObj interface{}) {
			if reflect.DeepEqual(oldObj.(*corev1alpha.NodeContribution).Status, newObj.(*corev1alpha.NodeContribution).Status) ||
				newObj.(*corev1alpha.NodeContribution).Status.State == inqueue {
				event.key, err = cache.MetaNamespaceKeyFunc(newObj)
				event.function = update
				log.Infof("Update nodecontribution: %s", event.key)
				if err == nil {
					queue.Add(event)
				}
			}
		},
		DeleteFunc: func(obj interface{}) {
			// DeletionHandlingMetaNamsespaceKeyFunc helps to check the existence of the object while it is still contained in the index.
			// Put the resource object into a key
			event.key, err = cache.DeletionHandlingMetaNamespaceKeyFunc(obj)
			event.function = delete
			log.Infof("Delete nodecontribution: %s", event.key)
			if err == nil {
				queue.Add(event)
			}
		},
	})
	nodeInformer := cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				return clientset.CoreV1().Nodes().List(context.TODO(), options)
			},
			// This function watches all changes/updates of nodes
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				return clientset.CoreV1().Nodes().Watch(context.TODO(), options)
			},
		},
		&corev1.Node{},
		0,
		cache.Indexers{},
	)
	nodeInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		UpdateFunc: func(old, new interface{}) {
			oldObj := old.(*corev1.Node)
			newObj := new.(*corev1.Node)
			oldReady := node.GetConditionReadyStatus(oldObj)
			newReady := node.GetConditionReadyStatus(newObj)
			for _, owner := range newObj.GetOwnerReferences() {
				if owner.Kind == "NodeContribution" {
					nodeContribution, err := edgenetClientset.CoreV1alpha().NodeContributions().Get(context.TODO(), owner.Name, metav1.GetOptions{})
					if err == nil {
						nodeName := fmt.Sprintf("%s.edge-net.io", nodeContribution.GetName())
						if newObj.GetName() == nodeName {
							if (oldReady == falseStr && newReady == trueStr) ||
								(oldReady == unknownStr && newReady == trueStr) {
								if nodeContribution.Status.State != success {
									nodeContribution.Status.State = success
									nodeContribution.Status.Message = append(nodeContribution.Status.Message, statusDict["successful"])
									edgenetClientset.CoreV1alpha().NodeContributions().UpdateStatus(context.TODO(), nodeContribution, metav1.UpdateOptions{})
								}
							} else if (oldReady == trueStr && newReady == falseStr) ||
								(oldReady == trueStr && newReady == unknownStr) {
								if nodeContribution.Status.State != failure {
									nodeContribution.Status.State = failure
									nodeContribution.Status.Message = append(nodeContribution.Status.Message, statusDict["failure"])
									edgenetClientset.CoreV1alpha().NodeContributions().UpdateStatus(context.TODO(), nodeContribution, metav1.UpdateOptions{})
								}
							}
							if (oldObj.Spec.Unschedulable == true && newObj.Spec.Unschedulable == false) ||
								(oldObj.Spec.Unschedulable == false && newObj.Spec.Unschedulable == true) {
								if nodeContribution.Spec.Enabled == newObj.Spec.Unschedulable {
									node.SetNodeScheduling(newObj.GetName(), !nodeContribution.Spec.Enabled)
								}
							}
						}
					}
				}
			}
		},
		DeleteFunc: func(obj interface{}) {
			log.Println("Node Deleted Event")
		},
	})
	controller := controller{
		logger:       log.NewEntry(log.New()),
		informer:     informer,
		nodeInformer: nodeInformer,
		queue:        queue,
		handler:      NCHandler,
	}

	// A channel to terminate elegantly
	stopCh := make(chan struct{})
	defer close(stopCh)
	// Run the controller loop as a background task to start processing resources
	go controller.run(stopCh, clientset, edgenetClientset)
	// A channel to observe OS signals for smooth shut down
	sigTerm := make(chan os.Signal, 1)
	signal.Notify(sigTerm, syscall.SIGTERM)
	signal.Notify(sigTerm, syscall.SIGINT)
	<-sigTerm
}

// Run starts the controller loop
func (c *controller) run(stopCh <-chan struct{}, clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
	// A Go panic which includes logging and terminating
	defer utilruntime.HandleCrash()
	// Shutdown after all goroutines have done
	defer c.queue.ShutDown()
	c.logger.Info("run: initiating")
	c.handler.Init(clientset, edgenetClientset)
	// Run the informer to list and watch resources
	go c.informer.Run(stopCh)
	go c.nodeInformer.Run(stopCh)

	// Synchronization to settle resources one
	if !cache.WaitForCacheSync(stopCh, c.informer.HasSynced, c.nodeInformer.HasSynced) {
		utilruntime.HandleError(fmt.Errorf("Error syncing cache"))
		return
	}
	c.logger.Info("run: cache sync complete")
	// Operate the runWorker
	go wait.Until(c.runWorker, time.Second, stopCh)

	<-stopCh
}

// To process new objects added to the queue
func (c *controller) runWorker() {
	log.Info("runWorker: starting")
	// Run processNextItem for all the changes
	for c.processNextItem() {
		log.Info("runWorker: processing next item")
	}

	log.Info("runWorker: completed")
}

// This function deals with the queue and sends each item in it to the specified handler to be processed.
func (c *controller) processNextItem() bool {
	log.Info("processNextItem: start")
	// Fetch the next item of the queue
	event, quit := c.queue.Get()
	if quit {
		return false
	}
	defer c.queue.Done(event)
	// Get the key string
	keyRaw := event.(informerevent).key
	// Use the string key to get the object from the indexer
	item, exists, err := c.informer.GetIndexer().GetByKey(keyRaw)
	if err != nil {
		if c.queue.NumRequeues(event.(informerevent).key) < 5 {
			c.logger.Errorf("Controller.processNextItem: Failed processing item with key %s with error %v, retrying", event.(informerevent).key, err)
			c.queue.AddRateLimited(event.(informerevent).key)
		} else {
			c.logger.Errorf("Controller.processNextItem: Failed processing item with key %s with error %v, no more retries", event.(informerevent).key, err)
			c.queue.Forget(event.(informerevent).key)
			utilruntime.HandleError(err)
		}
	}

	if !exists {
		if event.(informerevent).function == delete {
			c.logger.Infof("Controller.processNextItem: object deleted detected: %s", keyRaw)
			c.handler.ObjectDeleted(item)
		}
	} else {
		if event.(informerevent).function == create {
			c.logger.Infof("Controller.processNextItem: object created detected: %s", keyRaw)
			c.handler.ObjectCreatedOrUpdated(item)
		} else if event.(informerevent).function == update {
			c.logger.Infof("Controller.processNextItem: object updated detected: %s", keyRaw)
			c.handler.ObjectCreatedOrUpdated(item)
		}
	}
	c.queue.Forget(event.(informerevent).key)

	return true
}
