apiVersion: edgenet.io/v1alpha
kind: GeoLocation
metadata:
  name: geo-polygon
spec:
  deployment:
    - test1
  type: polygon
  value: 
    - "[
    [
      2.2150567,
      48.8947616
    ],
    [
      2.2040704,
      48.8084639
    ],
    [
      2.3393396,
      48.7835862
    ],
    [
      2.4519494,
      48.8416903
    ],
    [
      2.3932412,
      48.9171024
    ]
  ]"