apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequestControl
metadata:
  name: edgenet-cluster
spec:
  match:
    kinds:
      - apiGroups: ["apps.edgenet.io"]
        kinds: ["AuthorityRequest", "UserRegistrationRequest"]
  parameters:
    values:
      - false
