apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RoleBindingLimitation
metadata:
  name: edgenet-cluster
spec:
  match:
    namespaceSelector:
      matchExpressions:
      - key: owner
        operator: In
        values: ["tenant","slice","team"]
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["RoleBinding"]
  parameters:
    roles:
      - kind: Role
        name: ["user", "slice", "team", "tenant"]
