apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RoleLimitation
metadata:
  name: tenant
spec:
  match:
    namespaceSelector:
      matchExpressions:
      - key: owner
        operator: In
        values: ["tenant"]
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role"]
  parameters:
    rules:
      - resource: users
        verbs: ["*"]
      - resource: acceptableusepolicies
        verbs: ["get", "list"]
      - resource: userregistrationrequests
        verbs: ["*"]
      - resource: userregistrationrequests/status
        verbs: ["*"]
      - resource: slices
        verbs: ["*"]
      - resource: slices/status
        verbs: ["*"]
      - resource: teams
        verbs: ["*"]
      - resource: teams/status
        verbs: ["*"]
      - resource: nodecontributions
        verbs: ["*"]
      - resource: roles
        verbs: ["*"]
      - resource: rolebindings
        verbs: ["*"]
