apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RoleBindingLimitation
metadata:
  name: clusterrole
spec:
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["RoleBinding"]
  parameters:
    roles:
      - kind: ClusterRole
        name: ["edgenet:tenant-admin", "edgenet:tenant-collaborator", "edgenet:tenant-owner"]
