apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: rolelimitation
spec:
  crd:
    spec:
      names:
        kind: RoleLimitation
        listKind: RoleLimitationList
        plural: rolelimitations
        singular: rolelimitation
      validation:
        openAPIV3Schema:
          properties:
            spec:
              required:
                - rules
              rules:
                type: array
                items:
                  type: object
                  required:
                    - resource
                  properties:
                    resource:
                      type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package rolelimitation

        violation[{"msg": msg, "details": {"restricted_resources": restricted_resources}}] {
        restricted_resources[resource]
        count(restricted_resources) > 0
        not admin
        msg := sprintf("Resources shouldn't include prohibited ones in %s namespace: %v", [input.review.object.metadata.namespace, restricted_resources])
        }

        admin {
        "system:masters" == input.review.userInfo.groups[_]
        }

        restricted_resources[resource] {
        some i, j
        resource := input.review.object.rules[i].resources[j]
        matches_any(resource)
        }

        matches_any(resource) {
        some k
        param_resource := input.parameters.rules[k].resource
        resource == param_resource
        }
