apiVersion: apps.edgenet.io/v1alpha
kind: Authority
metadata:
  name: sorbonne-university
spec:
  fullname: Sorbonne University
  shortname: SU
  url: http://www.sorbonne-universite.fr/
  address:
    street: 4 place Jussieu, boite 169
    zip: "75005"
    city: Paris
    region: Île-de-France
    country: France
  contact:
    username: usersu
    firstname: Firstname
    lastname: Lastname
    email: usersu@lip6.fr
    phone: "+33XXXXXXXXX"
