apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: template-binding
  namespace: template
subjects:
- kind: User
  name: template
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
