# DaemonSet of Hello World exercise
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hello-world-new
spec:
  template:
    metadata:
      labels:
        app: hello-world-new
    spec:
      hostNetwork: true
      containers:
        - name: hello-world-new
          image: tutum/curl
          command: ["/bin/sh"]
          args: ["-c", "while true; sleep 60; do curl http://princeton.edge-net.io:5000/hello/$(hostname)/<username>; sleep 7200; done"]
---
# SelectiveDeployment to take Hello World DaemonSet under control
apiVersion: edgenet.io/v1alpha
kind: SelectiveDeployment
metadata:
  name: hello-world-new
spec:
  controller:
    - type: DaemonSet
      name: hello-world-new
  type: Polygon
  selector:
    - value: "[ [ 2.2150567, 48.8947616 ], [ 2.2040704, 48.8084639 ], [ 2.3393396, 48.7835862 ], [ 2.4519494, 48.8416903 ], [ 2.3932412, 48.9171024 ] ]"
      operator: In
      count: 0
    - value: "[ [ -129.4628906, 49.325122 ], [ -116.1914063, 51.2344074 ], [ -97.3828125, 26.1159859 ], [ -109.5996094, 21.4530686 ] ]"
      operator: In
      count: 0
