/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "headnode/pkg/apis/apps/v1alpha"
	scheme "headnode/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AuthorityRequestsGetter has a method to return a AuthorityRequestInterface.
// A group's client should implement this interface.
type AuthorityRequestsGetter interface {
	AuthorityRequests() AuthorityRequestInterface
}

// AuthorityRequestInterface has methods to work with AuthorityRequest resources.
type AuthorityRequestInterface interface {
	Create(*v1alpha.AuthorityRequest) (*v1alpha.AuthorityRequest, error)
	Update(*v1alpha.AuthorityRequest) (*v1alpha.AuthorityRequest, error)
	UpdateStatus(*v1alpha.AuthorityRequest) (*v1alpha.AuthorityRequest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.AuthorityRequest, error)
	List(opts v1.ListOptions) (*v1alpha.AuthorityRequestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.AuthorityRequest, err error)
	AuthorityRequestExpansion
}

// authorityRequests implements AuthorityRequestInterface
type authorityRequests struct {
	client rest.Interface
}

// newAuthorityRequests returns a AuthorityRequests
func newAuthorityRequests(c *AppsV1alphaClient) *authorityRequests {
	return &authorityRequests{
		client: c.RESTClient(),
	}
}

// Get takes name of the authorityRequest, and returns the corresponding authorityRequest object, and an error if there is any.
func (c *authorityRequests) Get(name string, options v1.GetOptions) (result *v1alpha.AuthorityRequest, err error) {
	result = &v1alpha.AuthorityRequest{}
	err = c.client.Get().
		Resource("authorityrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AuthorityRequests that match those selectors.
func (c *authorityRequests) List(opts v1.ListOptions) (result *v1alpha.AuthorityRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.AuthorityRequestList{}
	err = c.client.Get().
		Resource("authorityrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested authorityRequests.
func (c *authorityRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("authorityrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a authorityRequest and creates it.  Returns the server's representation of the authorityRequest, and an error, if there is any.
func (c *authorityRequests) Create(authorityRequest *v1alpha.AuthorityRequest) (result *v1alpha.AuthorityRequest, err error) {
	result = &v1alpha.AuthorityRequest{}
	err = c.client.Post().
		Resource("authorityrequests").
		Body(authorityRequest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a authorityRequest and updates it. Returns the server's representation of the authorityRequest, and an error, if there is any.
func (c *authorityRequests) Update(authorityRequest *v1alpha.AuthorityRequest) (result *v1alpha.AuthorityRequest, err error) {
	result = &v1alpha.AuthorityRequest{}
	err = c.client.Put().
		Resource("authorityrequests").
		Name(authorityRequest.Name).
		Body(authorityRequest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *authorityRequests) UpdateStatus(authorityRequest *v1alpha.AuthorityRequest) (result *v1alpha.AuthorityRequest, err error) {
	result = &v1alpha.AuthorityRequest{}
	err = c.client.Put().
		Resource("authorityrequests").
		Name(authorityRequest.Name).
		SubResource("status").
		Body(authorityRequest).
		Do().
		Into(result)
	return
}

// Delete takes name of the authorityRequest and deletes it. Returns an error if one occurs.
func (c *authorityRequests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("authorityrequests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *authorityRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("authorityrequests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched authorityRequest.
func (c *authorityRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.AuthorityRequest, err error) {
	result = &v1alpha.AuthorityRequest{}
	err = c.client.Patch(pt).
		Resource("authorityrequests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
