/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "edgenet/pkg/apis/apps/v1alpha"
	scheme "edgenet/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EmailVerificationsGetter has a method to return a EmailVerificationInterface.
// A group's client should implement this interface.
type EmailVerificationsGetter interface {
	EmailVerifications(namespace string) EmailVerificationInterface
}

// EmailVerificationInterface has methods to work with EmailVerification resources.
type EmailVerificationInterface interface {
	Create(*v1alpha.EmailVerification) (*v1alpha.EmailVerification, error)
	Update(*v1alpha.EmailVerification) (*v1alpha.EmailVerification, error)
	UpdateStatus(*v1alpha.EmailVerification) (*v1alpha.EmailVerification, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.EmailVerification, error)
	List(opts v1.ListOptions) (*v1alpha.EmailVerificationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.EmailVerification, err error)
	EmailVerificationExpansion
}

// emailVerifications implements EmailVerificationInterface
type emailVerifications struct {
	client rest.Interface
	ns     string
}

// newEmailVerifications returns a EmailVerifications
func newEmailVerifications(c *AppsV1alphaClient, namespace string) *emailVerifications {
	return &emailVerifications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the emailVerification, and returns the corresponding emailVerification object, and an error if there is any.
func (c *emailVerifications) Get(name string, options v1.GetOptions) (result *v1alpha.EmailVerification, err error) {
	result = &v1alpha.EmailVerification{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("emailverifications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EmailVerifications that match those selectors.
func (c *emailVerifications) List(opts v1.ListOptions) (result *v1alpha.EmailVerificationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.EmailVerificationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("emailverifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested emailVerifications.
func (c *emailVerifications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("emailverifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a emailVerification and creates it.  Returns the server's representation of the emailVerification, and an error, if there is any.
func (c *emailVerifications) Create(emailVerification *v1alpha.EmailVerification) (result *v1alpha.EmailVerification, err error) {
	result = &v1alpha.EmailVerification{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("emailverifications").
		Body(emailVerification).
		Do().
		Into(result)
	return
}

// Update takes the representation of a emailVerification and updates it. Returns the server's representation of the emailVerification, and an error, if there is any.
func (c *emailVerifications) Update(emailVerification *v1alpha.EmailVerification) (result *v1alpha.EmailVerification, err error) {
	result = &v1alpha.EmailVerification{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("emailverifications").
		Name(emailVerification.Name).
		Body(emailVerification).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *emailVerifications) UpdateStatus(emailVerification *v1alpha.EmailVerification) (result *v1alpha.EmailVerification, err error) {
	result = &v1alpha.EmailVerification{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("emailverifications").
		Name(emailVerification.Name).
		SubResource("status").
		Body(emailVerification).
		Do().
		Into(result)
	return
}

// Delete takes name of the emailVerification and deletes it. Returns an error if one occurs.
func (c *emailVerifications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("emailverifications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *emailVerifications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("emailverifications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched emailVerification.
func (c *emailVerifications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.EmailVerification, err error) {
	result = &v1alpha.EmailVerification{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("emailverifications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
