/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "edgenet/pkg/apis/apps/v1alpha"
	scheme "edgenet/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SelectiveDeploymentsGetter has a method to return a SelectiveDeploymentInterface.
// A group's client should implement this interface.
type SelectiveDeploymentsGetter interface {
	SelectiveDeployments(namespace string) SelectiveDeploymentInterface
}

// SelectiveDeploymentInterface has methods to work with SelectiveDeployment resources.
type SelectiveDeploymentInterface interface {
	Create(*v1alpha.SelectiveDeployment) (*v1alpha.SelectiveDeployment, error)
	Update(*v1alpha.SelectiveDeployment) (*v1alpha.SelectiveDeployment, error)
	UpdateStatus(*v1alpha.SelectiveDeployment) (*v1alpha.SelectiveDeployment, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.SelectiveDeployment, error)
	List(opts v1.ListOptions) (*v1alpha.SelectiveDeploymentList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SelectiveDeployment, err error)
	SelectiveDeploymentExpansion
}

// selectiveDeployments implements SelectiveDeploymentInterface
type selectiveDeployments struct {
	client rest.Interface
	ns     string
}

// newSelectiveDeployments returns a SelectiveDeployments
func newSelectiveDeployments(c *AppsV1alphaClient, namespace string) *selectiveDeployments {
	return &selectiveDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the selectiveDeployment, and returns the corresponding selectiveDeployment object, and an error if there is any.
func (c *selectiveDeployments) Get(name string, options v1.GetOptions) (result *v1alpha.SelectiveDeployment, err error) {
	result = &v1alpha.SelectiveDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("selectivedeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SelectiveDeployments that match those selectors.
func (c *selectiveDeployments) List(opts v1.ListOptions) (result *v1alpha.SelectiveDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.SelectiveDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("selectivedeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested selectiveDeployments.
func (c *selectiveDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("selectivedeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a selectiveDeployment and creates it.  Returns the server's representation of the selectiveDeployment, and an error, if there is any.
func (c *selectiveDeployments) Create(selectiveDeployment *v1alpha.SelectiveDeployment) (result *v1alpha.SelectiveDeployment, err error) {
	result = &v1alpha.SelectiveDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("selectivedeployments").
		Body(selectiveDeployment).
		Do().
		Into(result)
	return
}

// Update takes the representation of a selectiveDeployment and updates it. Returns the server's representation of the selectiveDeployment, and an error, if there is any.
func (c *selectiveDeployments) Update(selectiveDeployment *v1alpha.SelectiveDeployment) (result *v1alpha.SelectiveDeployment, err error) {
	result = &v1alpha.SelectiveDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("selectivedeployments").
		Name(selectiveDeployment.Name).
		Body(selectiveDeployment).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *selectiveDeployments) UpdateStatus(selectiveDeployment *v1alpha.SelectiveDeployment) (result *v1alpha.SelectiveDeployment, err error) {
	result = &v1alpha.SelectiveDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("selectivedeployments").
		Name(selectiveDeployment.Name).
		SubResource("status").
		Body(selectiveDeployment).
		Do().
		Into(result)
	return
}

// Delete takes name of the selectiveDeployment and deletes it. Returns an error if one occurs.
func (c *selectiveDeployments) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("selectivedeployments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *selectiveDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("selectivedeployments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched selectiveDeployment.
func (c *selectiveDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SelectiveDeployment, err error) {
	result = &v1alpha.SelectiveDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("selectivedeployments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
