/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "headnode/pkg/apis/apps/v1alpha"
	scheme "headnode/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SitesGetter has a method to return a SiteInterface.
// A group's client should implement this interface.
type SitesGetter interface {
	Sites() SiteInterface
}

// SiteInterface has methods to work with Site resources.
type SiteInterface interface {
	Create(*v1alpha.Site) (*v1alpha.Site, error)
	Update(*v1alpha.Site) (*v1alpha.Site, error)
	UpdateStatus(*v1alpha.Site) (*v1alpha.Site, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.Site, error)
	List(opts v1.ListOptions) (*v1alpha.SiteList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.Site, err error)
	SiteExpansion
}

// sites implements SiteInterface
type sites struct {
	client rest.Interface
}

// newSites returns a Sites
func newSites(c *AppsV1alphaClient) *sites {
	return &sites{
		client: c.RESTClient(),
	}
}

// Get takes name of the site, and returns the corresponding site object, and an error if there is any.
func (c *sites) Get(name string, options v1.GetOptions) (result *v1alpha.Site, err error) {
	result = &v1alpha.Site{}
	err = c.client.Get().
		Resource("sites").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Sites that match those selectors.
func (c *sites) List(opts v1.ListOptions) (result *v1alpha.SiteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.SiteList{}
	err = c.client.Get().
		Resource("sites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sites.
func (c *sites) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("sites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a site and creates it.  Returns the server's representation of the site, and an error, if there is any.
func (c *sites) Create(site *v1alpha.Site) (result *v1alpha.Site, err error) {
	result = &v1alpha.Site{}
	err = c.client.Post().
		Resource("sites").
		Body(site).
		Do().
		Into(result)
	return
}

// Update takes the representation of a site and updates it. Returns the server's representation of the site, and an error, if there is any.
func (c *sites) Update(site *v1alpha.Site) (result *v1alpha.Site, err error) {
	result = &v1alpha.Site{}
	err = c.client.Put().
		Resource("sites").
		Name(site.Name).
		Body(site).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sites) UpdateStatus(site *v1alpha.Site) (result *v1alpha.Site, err error) {
	result = &v1alpha.Site{}
	err = c.client.Put().
		Resource("sites").
		Name(site.Name).
		SubResource("status").
		Body(site).
		Do().
		Into(result)
	return
}

// Delete takes name of the site and deletes it. Returns an error if one occurs.
func (c *sites) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("sites").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sites) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("sites").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched site.
func (c *sites) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.Site, err error) {
	result = &v1alpha.Site{}
	err = c.client.Patch(pt).
		Resource("sites").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
