/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "headnode/pkg/apis/apps/v1alpha"
	scheme "headnode/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SiteRegistrationRequestsGetter has a method to return a SiteRegistrationRequestInterface.
// A group's client should implement this interface.
type SiteRegistrationRequestsGetter interface {
	SiteRegistrationRequests() SiteRegistrationRequestInterface
}

// SiteRegistrationRequestInterface has methods to work with SiteRegistrationRequest resources.
type SiteRegistrationRequestInterface interface {
	Create(*v1alpha.SiteRegistrationRequest) (*v1alpha.SiteRegistrationRequest, error)
	Update(*v1alpha.SiteRegistrationRequest) (*v1alpha.SiteRegistrationRequest, error)
	UpdateStatus(*v1alpha.SiteRegistrationRequest) (*v1alpha.SiteRegistrationRequest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.SiteRegistrationRequest, error)
	List(opts v1.ListOptions) (*v1alpha.SiteRegistrationRequestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SiteRegistrationRequest, err error)
	SiteRegistrationRequestExpansion
}

// siteRegistrationRequests implements SiteRegistrationRequestInterface
type siteRegistrationRequests struct {
	client rest.Interface
}

// newSiteRegistrationRequests returns a SiteRegistrationRequests
func newSiteRegistrationRequests(c *AppsV1alphaClient) *siteRegistrationRequests {
	return &siteRegistrationRequests{
		client: c.RESTClient(),
	}
}

// Get takes name of the siteRegistrationRequest, and returns the corresponding siteRegistrationRequest object, and an error if there is any.
func (c *siteRegistrationRequests) Get(name string, options v1.GetOptions) (result *v1alpha.SiteRegistrationRequest, err error) {
	result = &v1alpha.SiteRegistrationRequest{}
	err = c.client.Get().
		Resource("siteregistrationrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SiteRegistrationRequests that match those selectors.
func (c *siteRegistrationRequests) List(opts v1.ListOptions) (result *v1alpha.SiteRegistrationRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.SiteRegistrationRequestList{}
	err = c.client.Get().
		Resource("siteregistrationrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested siteRegistrationRequests.
func (c *siteRegistrationRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("siteregistrationrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a siteRegistrationRequest and creates it.  Returns the server's representation of the siteRegistrationRequest, and an error, if there is any.
func (c *siteRegistrationRequests) Create(siteRegistrationRequest *v1alpha.SiteRegistrationRequest) (result *v1alpha.SiteRegistrationRequest, err error) {
	result = &v1alpha.SiteRegistrationRequest{}
	err = c.client.Post().
		Resource("siteregistrationrequests").
		Body(siteRegistrationRequest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a siteRegistrationRequest and updates it. Returns the server's representation of the siteRegistrationRequest, and an error, if there is any.
func (c *siteRegistrationRequests) Update(siteRegistrationRequest *v1alpha.SiteRegistrationRequest) (result *v1alpha.SiteRegistrationRequest, err error) {
	result = &v1alpha.SiteRegistrationRequest{}
	err = c.client.Put().
		Resource("siteregistrationrequests").
		Name(siteRegistrationRequest.Name).
		Body(siteRegistrationRequest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *siteRegistrationRequests) UpdateStatus(siteRegistrationRequest *v1alpha.SiteRegistrationRequest) (result *v1alpha.SiteRegistrationRequest, err error) {
	result = &v1alpha.SiteRegistrationRequest{}
	err = c.client.Put().
		Resource("siteregistrationrequests").
		Name(siteRegistrationRequest.Name).
		SubResource("status").
		Body(siteRegistrationRequest).
		Do().
		Into(result)
	return
}

// Delete takes name of the siteRegistrationRequest and deletes it. Returns an error if one occurs.
func (c *siteRegistrationRequests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("siteregistrationrequests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *siteRegistrationRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("siteregistrationrequests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched siteRegistrationRequest.
func (c *siteRegistrationRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SiteRegistrationRequest, err error) {
	result = &v1alpha.SiteRegistrationRequest{}
	err = c.client.Patch(pt).
		Resource("siteregistrationrequests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
