/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "edgenet/pkg/apis/apps/v1alpha"
	scheme "edgenet/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TotalResourceQuotasGetter has a method to return a TotalResourceQuotaInterface.
// A group's client should implement this interface.
type TotalResourceQuotasGetter interface {
	TotalResourceQuotas() TotalResourceQuotaInterface
}

// TotalResourceQuotaInterface has methods to work with TotalResourceQuota resources.
type TotalResourceQuotaInterface interface {
	Create(*v1alpha.TotalResourceQuota) (*v1alpha.TotalResourceQuota, error)
	Update(*v1alpha.TotalResourceQuota) (*v1alpha.TotalResourceQuota, error)
	UpdateStatus(*v1alpha.TotalResourceQuota) (*v1alpha.TotalResourceQuota, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.TotalResourceQuota, error)
	List(opts v1.ListOptions) (*v1alpha.TotalResourceQuotaList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.TotalResourceQuota, err error)
	TotalResourceQuotaExpansion
}

// totalResourceQuotas implements TotalResourceQuotaInterface
type totalResourceQuotas struct {
	client rest.Interface
}

// newTotalResourceQuotas returns a TotalResourceQuotas
func newTotalResourceQuotas(c *AppsV1alphaClient) *totalResourceQuotas {
	return &totalResourceQuotas{
		client: c.RESTClient(),
	}
}

// Get takes name of the totalResourceQuota, and returns the corresponding totalResourceQuota object, and an error if there is any.
func (c *totalResourceQuotas) Get(name string, options v1.GetOptions) (result *v1alpha.TotalResourceQuota, err error) {
	result = &v1alpha.TotalResourceQuota{}
	err = c.client.Get().
		Resource("totalresourcequotas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TotalResourceQuotas that match those selectors.
func (c *totalResourceQuotas) List(opts v1.ListOptions) (result *v1alpha.TotalResourceQuotaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.TotalResourceQuotaList{}
	err = c.client.Get().
		Resource("totalresourcequotas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested totalResourceQuotas.
func (c *totalResourceQuotas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("totalresourcequotas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a totalResourceQuota and creates it.  Returns the server's representation of the totalResourceQuota, and an error, if there is any.
func (c *totalResourceQuotas) Create(totalResourceQuota *v1alpha.TotalResourceQuota) (result *v1alpha.TotalResourceQuota, err error) {
	result = &v1alpha.TotalResourceQuota{}
	err = c.client.Post().
		Resource("totalresourcequotas").
		Body(totalResourceQuota).
		Do().
		Into(result)
	return
}

// Update takes the representation of a totalResourceQuota and updates it. Returns the server's representation of the totalResourceQuota, and an error, if there is any.
func (c *totalResourceQuotas) Update(totalResourceQuota *v1alpha.TotalResourceQuota) (result *v1alpha.TotalResourceQuota, err error) {
	result = &v1alpha.TotalResourceQuota{}
	err = c.client.Put().
		Resource("totalresourcequotas").
		Name(totalResourceQuota.Name).
		Body(totalResourceQuota).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *totalResourceQuotas) UpdateStatus(totalResourceQuota *v1alpha.TotalResourceQuota) (result *v1alpha.TotalResourceQuota, err error) {
	result = &v1alpha.TotalResourceQuota{}
	err = c.client.Put().
		Resource("totalresourcequotas").
		Name(totalResourceQuota.Name).
		SubResource("status").
		Body(totalResourceQuota).
		Do().
		Into(result)
	return
}

// Delete takes name of the totalResourceQuota and deletes it. Returns an error if one occurs.
func (c *totalResourceQuotas) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("totalresourcequotas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *totalResourceQuotas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("totalresourcequotas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched totalResourceQuota.
func (c *totalResourceQuotas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.TotalResourceQuota, err error) {
	result = &v1alpha.TotalResourceQuota{}
	err = c.client.Patch(pt).
		Resource("totalresourcequotas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
