/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "edgenet/pkg/apis/apps/v1alpha"
	scheme "edgenet/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UserRegistrationRequestsGetter has a method to return a UserRegistrationRequestInterface.
// A group's client should implement this interface.
type UserRegistrationRequestsGetter interface {
	UserRegistrationRequests(namespace string) UserRegistrationRequestInterface
}

// UserRegistrationRequestInterface has methods to work with UserRegistrationRequest resources.
type UserRegistrationRequestInterface interface {
	Create(*v1alpha.UserRegistrationRequest) (*v1alpha.UserRegistrationRequest, error)
	Update(*v1alpha.UserRegistrationRequest) (*v1alpha.UserRegistrationRequest, error)
	UpdateStatus(*v1alpha.UserRegistrationRequest) (*v1alpha.UserRegistrationRequest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.UserRegistrationRequest, error)
	List(opts v1.ListOptions) (*v1alpha.UserRegistrationRequestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.UserRegistrationRequest, err error)
	UserRegistrationRequestExpansion
}

// userRegistrationRequests implements UserRegistrationRequestInterface
type userRegistrationRequests struct {
	client rest.Interface
	ns     string
}

// newUserRegistrationRequests returns a UserRegistrationRequests
func newUserRegistrationRequests(c *AppsV1alphaClient, namespace string) *userRegistrationRequests {
	return &userRegistrationRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the userRegistrationRequest, and returns the corresponding userRegistrationRequest object, and an error if there is any.
func (c *userRegistrationRequests) Get(name string, options v1.GetOptions) (result *v1alpha.UserRegistrationRequest, err error) {
	result = &v1alpha.UserRegistrationRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UserRegistrationRequests that match those selectors.
func (c *userRegistrationRequests) List(opts v1.ListOptions) (result *v1alpha.UserRegistrationRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha.UserRegistrationRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested userRegistrationRequests.
func (c *userRegistrationRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a userRegistrationRequest and creates it.  Returns the server's representation of the userRegistrationRequest, and an error, if there is any.
func (c *userRegistrationRequests) Create(userRegistrationRequest *v1alpha.UserRegistrationRequest) (result *v1alpha.UserRegistrationRequest, err error) {
	result = &v1alpha.UserRegistrationRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		Body(userRegistrationRequest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a userRegistrationRequest and updates it. Returns the server's representation of the userRegistrationRequest, and an error, if there is any.
func (c *userRegistrationRequests) Update(userRegistrationRequest *v1alpha.UserRegistrationRequest) (result *v1alpha.UserRegistrationRequest, err error) {
	result = &v1alpha.UserRegistrationRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		Name(userRegistrationRequest.Name).
		Body(userRegistrationRequest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *userRegistrationRequests) UpdateStatus(userRegistrationRequest *v1alpha.UserRegistrationRequest) (result *v1alpha.UserRegistrationRequest, err error) {
	result = &v1alpha.UserRegistrationRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		Name(userRegistrationRequest.Name).
		SubResource("status").
		Body(userRegistrationRequest).
		Do().
		Into(result)
	return
}

// Delete takes name of the userRegistrationRequest and deletes it. Returns an error if one occurs.
func (c *userRegistrationRequests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *userRegistrationRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("userregistrationrequests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched userRegistrationRequest.
func (c *userRegistrationRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.UserRegistrationRequest, err error) {
	result = &v1alpha.UserRegistrationRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("userregistrationrequests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
