# Copyright 2020 Sorbonne Université

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.core.edgenet.io
spec:
  group: core.edgenet.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Official Name
          type: string
          jsonPath: .spec.fullname
        - name: Short Name
          type: string
          jsonPath: .spec.shortname
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: City
          type: string
          jsonPath: .spec.address.city
        - name: Country
          type: string
          jsonPath: .spec.address.country
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - fullname
                - shortname
                - url
                - address
                - contact
                - user
                - enabled
              properties:
                fullname:
                  type: string
                shortname:
                  type: string
                url:
                  type: string
                address:
                  type: object
                  required:
                    - street
                    - zip
                    - city
                    - country
                  properties:
                    street:
                      type: string
                    zip:
                      type: string
                    city:
                      type: string
                    region:
                      type: string
                      description: region or state
                    country:
                      type: string
                contact:
                  type: object
                  required:
                    - firstname
                    - lastname
                    - email
                    - phone
                  properties:
                    firstname:
                      type: string
                    lastname:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                user:
                  type: array
                  nullable: false
                  items:
                    type: object
                    required:
                      - username
                      - firstname
                      - lastname
                      - email
                      - role
                    properties:
                      username:
                        type: string
                        pattern: "^[a-z0-9]*$"
                      firstname:
                        type: string
                      lastname:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                        enum:
                          - Owner
                          - Admin
                          - Collaborator
                      active:
                        type: boolean
                enabled:
                  type: boolean
            status:
              type: object
              properties:
                nodecontribution:
                  type: array
                  nullable: true
                  items:
                    type: string
                registrationrequest:
                  type: array
                  nullable: true
                  items:
                    type: string
                state:
                  type: string
                message:
                  type: array
                  items:
                    type: string
  scope: Cluster
  names:
    plural: tenants
    singular: tenant
    kind: Tenant
