apiVersion: edgenet.io/v1alpha
kind: SelectiveDeployment
metadata:
  name: city3
spec:
  controller:
    - [deployment, deployment3]
    - [deployment, deployment4]
  type: city
  value:
    - Seattle
