apiVersion: edgenet.io/v1alpha
kind: SelectiveDeployment
metadata:
  name: city1
spec:
  controller:
    - [deployment, deployment1]
    - [deployment, deployment2]
    - [deployment, deployment3]
  type: city
  value:
    - Paris
    - Los_Angeles
