apiVersion: edgenet.io/v1alpha
kind: SelectiveDeployment
metadata:
  name: country2
spec:
  controller:
    - [deployment, deployment1]
    - [deployment, deployment2]
  type: country
  value:
    - FR
