/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	geolocationv1alpha "headnode/pkg/apis/geolocation/v1alpha"
	versioned "headnode/pkg/client/clientset/versioned"
	internalinterfaces "headnode/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha "headnode/pkg/client/listers/geolocation/v1alpha"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GeoLocationInformer provides access to a shared informer and lister for
// GeoLocations.
type GeoLocationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha.GeoLocationLister
}

type geoLocationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGeoLocationInformer constructs a new informer for GeoLocation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGeoLocationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGeoLocationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGeoLocationInformer constructs a new informer for GeoLocation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGeoLocationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgenetV1alpha().GeoLocations(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgenetV1alpha().GeoLocations(namespace).Watch(options)
			},
		},
		&geolocationv1alpha.GeoLocation{},
		resyncPeriod,
		indexers,
	)
}

func (f *geoLocationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGeoLocationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *geoLocationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&geolocationv1alpha.GeoLocation{}, f.defaultInformer)
}

func (f *geoLocationInformer) Lister() v1alpha.GeoLocationLister {
	return v1alpha.NewGeoLocationLister(f.Informer().GetIndexer())
}
