apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: geolocations.edgenet.io
spec:
  group: edgenet.io
  version: v1alpha
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: geolocations
    singular: geolocation
    kind: GeoLocation
    shortNames:
    - geo
  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: .status.ready
    - name: Status
      type: string
      JSONPath: .status.state
    - name: Type
      type: string
      description: The type of geolocation filter
      JSONPath: .spec.type
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      required: [spec]
      properties:
        spec:
          required: [deployment,type,value]
          properties:
            deployment:
              type: array
              minimum: 1
            type:
              type: string
              minimum: 1
              maximum: 1
            value:
              type: array
              minimum: 1
