# Copyright 2019 Sorbonne Université

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: selectivedeployments.apps.edgenet.io
spec:
  group: apps.edgenet.io
  version: v1alpha
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: selectivedeployments
    singular: selectivedeployment
    kind: SelectiveDeployment
    shortNames:
      - sd
  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: .status.ready
    - name: Status
      type: string
      JSONPath: .status.state
    - name: Type
      type: string
      description: The type of selectivedeployment filter
      JSONPath: .spec.type
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        spec:
          required:
            - controller
            - type
            - selector
          properties:
            controller:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - Deployment
                      - DaemonSet
                      - StatefulSet
                  name:
                    type: string
              minimum: 1
            type:
              type: string
              enum:
                - City
                - State
                - Country
                - Continent
                - Polygon
            selector:
              type: array
              items:
                type: object
                properties:
                  value:
                    type: string
                  operator:
                    type: string
                    enum:
                      - In
                      - NotIn
                  count:
                    type: integer
                    description: The number of nodes that will be picked for this selector. 0 means no limitation.
                    minimum: 0
              minimum: 1
