# Copyright 2019 Sorbonne Université

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: totalresourcequotas.apps.edgenet.io
spec:
  group: apps.edgenet.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: CPU Usage
          type: string
          jsonPath: .status.used.cpu
        - name: Memory Usage
          type: string
          jsonPath: .status.used.memory
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - default
              properties:
                default:
                  type: object
                  required:
                    - cpu
                    - memory
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                custom:
                  type: array
                  items:
                    type: object
                    required:
                      - cpu
                      - memory
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      expires:
                        type: string
                        format: date
                contribution:
                  type: array
                  items:
                    type: object
                    required:
                      - node
                    properties:
                      node:
                        type: string
                      cpu:
                        type: string
                      memory:
                        type: string
                      reward:
                        type: object
                        required:
                          - status
                          - cpu
                          - memory
                        properties:
                          status:
                            type: string
                            enum:
                              - Active
                              - Deactive
                          cpu:
                            type: string
                          memory:
                            type: string
  scope: Cluster
  names:
    plural: totalresourcequotas
    singular: totalresourcequota
    kind: TotalResourceQuota
    shortNames:
      - trq
