# Copyright 2019 Sorbonne Université

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.apps.edgenet.io
spec:
  group: apps.edgenet.io
  version: v1alpha
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: users
    singular: user
    kind: User
  additionalPrinterColumns:
    - name: "First Name"
      type: string
      JSONPath: .spec.firstname
    - name: "Last Name"
      type: string
      JSONPath: .spec.lastname
    - name: Email
      type: string
      JSONPath: .spec.email
    - name: Profile
      type: string
      JSONPath: .spec.profile
    - name: Kubeconfig
      type: boolean
      JSONPath: .status.kubeconfig
    - name: AUP
      type: boolean
      JSONPath: .status.aup.accepted
    - name: Enabled
      type: boolean
      JSONPath: .status.enabled
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        spec:
          required:
            - firstname
            - lastname
            - email
            - password
            - profile
          properties:
            firstname:
              type: string
            lastname:
              type: string
            email:
              type: string
            password:
              type: string
              description: Secret
            profile:
              type: string
              enum:
                - Admin
                - PI
                - Tech
                - Default
            url:
              type: string
            bio:
              type: string
