/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha "headnode/pkg/apis/geolocation/v1alpha"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGeoLocations implements GeoLocationInterface
type FakeGeoLocations struct {
	Fake *FakeEdgenetV1alpha
	ns   string
}

var geolocationsResource = schema.GroupVersionResource{Group: "edgenet.io", Version: "v1alpha", Resource: "geolocations"}

var geolocationsKind = schema.GroupVersionKind{Group: "edgenet.io", Version: "v1alpha", Kind: "GeoLocation"}

// Get takes name of the geoLocation, and returns the corresponding geoLocation object, and an error if there is any.
func (c *FakeGeoLocations) Get(name string, options v1.GetOptions) (result *v1alpha.GeoLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(geolocationsResource, c.ns, name), &v1alpha.GeoLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.GeoLocation), err
}

// List takes label and field selectors, and returns the list of GeoLocations that match those selectors.
func (c *FakeGeoLocations) List(opts v1.ListOptions) (result *v1alpha.GeoLocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(geolocationsResource, geolocationsKind, c.ns, opts), &v1alpha.GeoLocationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.GeoLocationList{ListMeta: obj.(*v1alpha.GeoLocationList).ListMeta}
	for _, item := range obj.(*v1alpha.GeoLocationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested geoLocations.
func (c *FakeGeoLocations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(geolocationsResource, c.ns, opts))

}

// Create takes the representation of a geoLocation and creates it.  Returns the server's representation of the geoLocation, and an error, if there is any.
func (c *FakeGeoLocations) Create(geoLocation *v1alpha.GeoLocation) (result *v1alpha.GeoLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(geolocationsResource, c.ns, geoLocation), &v1alpha.GeoLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.GeoLocation), err
}

// Update takes the representation of a geoLocation and updates it. Returns the server's representation of the geoLocation, and an error, if there is any.
func (c *FakeGeoLocations) Update(geoLocation *v1alpha.GeoLocation) (result *v1alpha.GeoLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(geolocationsResource, c.ns, geoLocation), &v1alpha.GeoLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.GeoLocation), err
}

// Delete takes name of the geoLocation and deletes it. Returns an error if one occurs.
func (c *FakeGeoLocations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(geolocationsResource, c.ns, name), &v1alpha.GeoLocation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGeoLocations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(geolocationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha.GeoLocationList{})
	return err
}

// Patch applies the patch and returns the patched geoLocation.
func (c *FakeGeoLocations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.GeoLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(geolocationsResource, c.ns, name, pt, data, subresources...), &v1alpha.GeoLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.GeoLocation), err
}
