apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thisisatest-binding
  namespace: thisisatest
subjects:
- kind: User
  name: thisisatest
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
