/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	appsv1alpha "headnode/pkg/apis/apps/v1alpha"
	versioned "headnode/pkg/client/clientset/versioned"
	internalinterfaces "headnode/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha "headnode/pkg/client/listers/apps/v1alpha"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LoginInformer provides access to a shared informer and lister for
// Logins.
type LoginInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha.LoginLister
}

type loginInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLoginInformer constructs a new informer for Login type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLoginInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLoginInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLoginInformer constructs a new informer for Login type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLoginInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha().Logins(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha().Logins(namespace).Watch(options)
			},
		},
		&appsv1alpha.Login{},
		resyncPeriod,
		indexers,
	)
}

func (f *loginInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLoginInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *loginInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&appsv1alpha.Login{}, f.defaultInformer)
}

func (f *loginInformer) Lister() v1alpha.LoginLister {
	return v1alpha.NewLoginLister(f.Informer().GetIndexer())
}
