runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /downloads
  static_dir: downloads

- url: /update_nodes
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /update_configs
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /add_node
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301


- url: /get_secret
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /confirm_namespace
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /show_ip
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /show_headers
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /show_config
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /show_nodes
  script: portal.app
  login: optional
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: portal.app
  login: required
  secure: always
  redirect_http_response_code: 301

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin



# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
