apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - sorbonne-1
                - sorbonne-2
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
