/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

// AcceptableUsePolicyListerExpansion allows custom methods to be added to
// AcceptableUsePolicyLister.
type AcceptableUsePolicyListerExpansion interface{}

// AcceptableUsePolicyNamespaceListerExpansion allows custom methods to be added to
// AcceptableUsePolicyNamespaceLister.
type AcceptableUsePolicyNamespaceListerExpansion interface{}

// AuthorityListerExpansion allows custom methods to be added to
// AuthorityLister.
type AuthorityListerExpansion interface{}

// AuthorityRequestListerExpansion allows custom methods to be added to
// AuthorityRequestLister.
type AuthorityRequestListerExpansion interface{}

// EmailVerificationListerExpansion allows custom methods to be added to
// EmailVerificationLister.
type EmailVerificationListerExpansion interface{}

// EmailVerificationNamespaceListerExpansion allows custom methods to be added to
// EmailVerificationNamespaceLister.
type EmailVerificationNamespaceListerExpansion interface{}

// LoginListerExpansion allows custom methods to be added to
// LoginLister.
type LoginListerExpansion interface{}

// LoginNamespaceListerExpansion allows custom methods to be added to
// LoginNamespaceLister.
type LoginNamespaceListerExpansion interface{}

// NodeContributionListerExpansion allows custom methods to be added to
// NodeContributionLister.
type NodeContributionListerExpansion interface{}

// NodeContributionNamespaceListerExpansion allows custom methods to be added to
// NodeContributionNamespaceLister.
type NodeContributionNamespaceListerExpansion interface{}

// SelectiveDeploymentListerExpansion allows custom methods to be added to
// SelectiveDeploymentLister.
type SelectiveDeploymentListerExpansion interface{}

// SelectiveDeploymentNamespaceListerExpansion allows custom methods to be added to
// SelectiveDeploymentNamespaceLister.
type SelectiveDeploymentNamespaceListerExpansion interface{}

// SliceListerExpansion allows custom methods to be added to
// SliceLister.
type SliceListerExpansion interface{}

// SliceNamespaceListerExpansion allows custom methods to be added to
// SliceNamespaceLister.
type SliceNamespaceListerExpansion interface{}

// TeamListerExpansion allows custom methods to be added to
// TeamLister.
type TeamListerExpansion interface{}

// TeamNamespaceListerExpansion allows custom methods to be added to
// TeamNamespaceLister.
type TeamNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserNamespaceListerExpansion allows custom methods to be added to
// UserNamespaceLister.
type UserNamespaceListerExpansion interface{}

// UserRegistrationRequestListerExpansion allows custom methods to be added to
// UserRegistrationRequestLister.
type UserRegistrationRequestListerExpansion interface{}

// UserRegistrationRequestNamespaceListerExpansion allows custom methods to be added to
// UserRegistrationRequestNamespaceLister.
type UserRegistrationRequestNamespaceListerExpansion interface{}
