/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha "headnode/pkg/apis/apps/v1alpha"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuthorityRequests implements AuthorityRequestInterface
type FakeAuthorityRequests struct {
	Fake *FakeAppsV1alpha
}

var authorityrequestsResource = schema.GroupVersionResource{Group: "apps.edgenet.io", Version: "v1alpha", Resource: "authorityrequests"}

var authorityrequestsKind = schema.GroupVersionKind{Group: "apps.edgenet.io", Version: "v1alpha", Kind: "AuthorityRequest"}

// Get takes name of the authorityRequest, and returns the corresponding authorityRequest object, and an error if there is any.
func (c *FakeAuthorityRequests) Get(name string, options v1.GetOptions) (result *v1alpha.AuthorityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(authorityrequestsResource, name), &v1alpha.AuthorityRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.AuthorityRequest), err
}

// List takes label and field selectors, and returns the list of AuthorityRequests that match those selectors.
func (c *FakeAuthorityRequests) List(opts v1.ListOptions) (result *v1alpha.AuthorityRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(authorityrequestsResource, authorityrequestsKind, opts), &v1alpha.AuthorityRequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.AuthorityRequestList{ListMeta: obj.(*v1alpha.AuthorityRequestList).ListMeta}
	for _, item := range obj.(*v1alpha.AuthorityRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested authorityRequests.
func (c *FakeAuthorityRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(authorityrequestsResource, opts))
}

// Create takes the representation of a authorityRequest and creates it.  Returns the server's representation of the authorityRequest, and an error, if there is any.
func (c *FakeAuthorityRequests) Create(authorityRequest *v1alpha.AuthorityRequest) (result *v1alpha.AuthorityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(authorityrequestsResource, authorityRequest), &v1alpha.AuthorityRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.AuthorityRequest), err
}

// Update takes the representation of a authorityRequest and updates it. Returns the server's representation of the authorityRequest, and an error, if there is any.
func (c *FakeAuthorityRequests) Update(authorityRequest *v1alpha.AuthorityRequest) (result *v1alpha.AuthorityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(authorityrequestsResource, authorityRequest), &v1alpha.AuthorityRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.AuthorityRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuthorityRequests) UpdateStatus(authorityRequest *v1alpha.AuthorityRequest) (*v1alpha.AuthorityRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(authorityrequestsResource, "status", authorityRequest), &v1alpha.AuthorityRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.AuthorityRequest), err
}

// Delete takes name of the authorityRequest and deletes it. Returns an error if one occurs.
func (c *FakeAuthorityRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(authorityrequestsResource, name), &v1alpha.AuthorityRequest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuthorityRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(authorityrequestsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha.AuthorityRequestList{})
	return err
}

// Patch applies the patch and returns the patched authorityRequest.
func (c *FakeAuthorityRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.AuthorityRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(authorityrequestsResource, name, pt, data, subresources...), &v1alpha.AuthorityRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.AuthorityRequest), err
}
