/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha "headnode/pkg/apis/apps/v1alpha"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSiteRegistrationRequests implements SiteRegistrationRequestInterface
type FakeSiteRegistrationRequests struct {
	Fake *FakeAppsV1alpha
}

var siteregistrationrequestsResource = schema.GroupVersionResource{Group: "apps.edgenet.io", Version: "v1alpha", Resource: "siteregistrationrequests"}

var siteregistrationrequestsKind = schema.GroupVersionKind{Group: "apps.edgenet.io", Version: "v1alpha", Kind: "SiteRegistrationRequest"}

// Get takes name of the siteRegistrationRequest, and returns the corresponding siteRegistrationRequest object, and an error if there is any.
func (c *FakeSiteRegistrationRequests) Get(name string, options v1.GetOptions) (result *v1alpha.SiteRegistrationRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(siteregistrationrequestsResource, name), &v1alpha.SiteRegistrationRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.SiteRegistrationRequest), err
}

// List takes label and field selectors, and returns the list of SiteRegistrationRequests that match those selectors.
func (c *FakeSiteRegistrationRequests) List(opts v1.ListOptions) (result *v1alpha.SiteRegistrationRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(siteregistrationrequestsResource, siteregistrationrequestsKind, opts), &v1alpha.SiteRegistrationRequestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.SiteRegistrationRequestList{ListMeta: obj.(*v1alpha.SiteRegistrationRequestList).ListMeta}
	for _, item := range obj.(*v1alpha.SiteRegistrationRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested siteRegistrationRequests.
func (c *FakeSiteRegistrationRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(siteregistrationrequestsResource, opts))
}

// Create takes the representation of a siteRegistrationRequest and creates it.  Returns the server's representation of the siteRegistrationRequest, and an error, if there is any.
func (c *FakeSiteRegistrationRequests) Create(siteRegistrationRequest *v1alpha.SiteRegistrationRequest) (result *v1alpha.SiteRegistrationRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(siteregistrationrequestsResource, siteRegistrationRequest), &v1alpha.SiteRegistrationRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.SiteRegistrationRequest), err
}

// Update takes the representation of a siteRegistrationRequest and updates it. Returns the server's representation of the siteRegistrationRequest, and an error, if there is any.
func (c *FakeSiteRegistrationRequests) Update(siteRegistrationRequest *v1alpha.SiteRegistrationRequest) (result *v1alpha.SiteRegistrationRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(siteregistrationrequestsResource, siteRegistrationRequest), &v1alpha.SiteRegistrationRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.SiteRegistrationRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSiteRegistrationRequests) UpdateStatus(siteRegistrationRequest *v1alpha.SiteRegistrationRequest) (*v1alpha.SiteRegistrationRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(siteregistrationrequestsResource, "status", siteRegistrationRequest), &v1alpha.SiteRegistrationRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.SiteRegistrationRequest), err
}

// Delete takes name of the siteRegistrationRequest and deletes it. Returns an error if one occurs.
func (c *FakeSiteRegistrationRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(siteregistrationrequestsResource, name), &v1alpha.SiteRegistrationRequest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSiteRegistrationRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(siteregistrationrequestsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha.SiteRegistrationRequestList{})
	return err
}

// Patch applies the patch and returns the patched siteRegistrationRequest.
func (c *FakeSiteRegistrationRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SiteRegistrationRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(siteregistrationrequestsResource, name, pt, data, subresources...), &v1alpha.SiteRegistrationRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.SiteRegistrationRequest), err
}
