name: Testing

on: 
  push:
    branches:
    - master
    - release-*
  pull_request:
    types: [opened]

jobs:
  test:
    name: Unit Testing with Coverage
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16'

    - name: Check out the repo
      uses: actions/checkout@v2
      with:
          lfs: true

    - name: Install dependencies
      run: |
        go mod download
        go mod vendor
        make bootstrap

    - name: Run Unit tests
      run: |
        go test -covermode atomic -coverprofile=covprofile ./...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: $(go env GOPATH)/bin/goveralls -coverprofile=covprofile -service=github -ignore='pkg/generated/*,pkg/generated/*/*,pkg/generated/*/*/*,pkg/generated/*/*/*/*,pkg/generated/*/*/*/*/*,vendor/*,vendor/*/*,vendor/*/*/*,vendor/*/*/*/*,vendor/*/*/*/*/*'